#!/bin/sh

CFENGINE_DIR=/var/cfengine
CFENGINE_MASTERFILES_DIR=$CFENGINE_DIR/masterfiles
CFENGINE_SERVICES_DIR=$CFENGINE_MASTERFILES_DIR/services
CFENGINE_TEMPLATES_DIR=$CFENGINE_DIR/templates

SURFSARA_LIB="masterfiles/lib/surfsara"
SURFSARA_AUTORUN_SERVICE="masterfiles/services/autorun/surfsara.cf"

SURFSARA_TEMPLATES="templates"
SURFSARA_SERVICES="services"


### Functions 
print_usage()
{
    echo "$(basename $0) [-d <cfengine_dir]"
}

while getopts "hd:" opt
do
    case $opt in
      d)
        CFENGINE_DIR="$OPTARG"
        ;;
      h)
        print_usage
        exit 0
        ;;
      \?)
        echo "-----------------------------------------------------"
        echo "            Received an invalid option"
        echo "-----------------------------------------------------"
        print_usage
        exit 1
        ;;
    esac
done

if [ ! -d $CFENGINE_MASTERFILES_DIR ]
then
    echo "CFengine masterfiles Directory: $CFENGINE_MASTERFILES_DIR does NOT exists"
    exit 1
fi

if [ -d $CFENGINE_MASTERFILES_DIR/lib/surfsara ]
then
    ### what to do about def.cf
    echo "Updating surfsara library and autorun file"
    cp  $SURFSARA_LIB/* $CFENGINE_MASTERFILES_DIR/lib/surfsara
else
    echo "Installing surfsara library and autorun file"
    cp -PR $SURFSARA_LIB $CFENGINE_MASTERFILES_DIR/lib/
fi

### THis is always updated
cp $SURFSARA_AUTORUN_SERVICE $CFENGINE_SERVICES_DIR/autorun


if [  -d $CFENGINE_SERVICES_DIR/surfsara ]
then
    echo "Updating surfsara services"
    cp $SURFSARA_SERVICES/* $CFENGINE_SERVICES_DIR/surfsara
else
    echo "Installing surfsara services"
    mkdir $CFENGINE_SERVICES_DIR/surfsara 
    cp $SURFSARA_SERVICES/* $CFENGINE_SERVICES_DIR/surfsara
fi

cd  $SURFSARA_TEMPLATES || exit 1

for d in *
do
        if [ -d $CFENGINE_TEMPLATES_DIR/$d ]
        then
            echo "Updating mustache template(s) and default.json: $d"
            templates=$(ls $d/*.mustache 2>/dev/null)
            if [ ! -z "$templates" ]
            then
                cp $d/*.mustache $CFENGINE_TEMPLATES_DIR/$d
            fi
            cp $d/json/default.json $CFENGINE_TEMPLATES_DIR/$d/json
        else
            echo "Installing  mustache template(s) and json file(s)"
            cp -PR $d $CFENGINE_TEMPLATES_DIR
        fi
done
